update vendor to openshift 3.7.0

diff --git a/vendor/github.com/openshift/origin/cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/Makefile b/vendor/github.com/openshift/origin/cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/Makefile
--- a/vendor/github.com/openshift/origin/cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/Makefile
+++ b/vendor/github.com/openshift/origin/cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/Makefile
@@ -33,6 +33,7 @@ SRC_DIRS       = $(shell sh -c "find $(TOP_SRC_DIRS) -name \\*.go \
 TEST_DIRS     ?= $(shell sh -c "find $(TOP_SRC_DIRS) -name \\*_test.go \
                    -exec dirname {} \\; | sort | uniq")
 VERSION       ?= $(shell git describe --always --abbrev=7 --dirty)
+BUILD_LDFLAGS  = $(shell build/version.sh $(ROOT) $(SC_PKG))
 
 # Run stat against /dev/null and check if it has any stdout output.
 # If stdout is blank, we are detecting bsd-stat because stat it has
@@ -45,33 +46,50 @@ endif
 
 NEWEST_GO_FILE = $(shell find $(SRC_DIRS) -name \*.go -exec $(STAT) {} \; \
                    | sort -r | head -n 1 | sed "s/.* //")
+
+NEWEST_E2ETEST_SOURCE = $(shell find test/e2e -name \*.go -exec $(STAT) {} \; \
+                   | sort -r | head -n 1 | sed "s/.* //")
+
 TYPES_FILES    = $(shell find pkg/apis -name types.go)
-GO_VERSION     = 1.8
+GO_VERSION     = 1.9
+
+ALL_ARCH=amd64 arm arm64 ppc64le s390x
 
 PLATFORM?=linux
 ARCH?=amd64
 
+# TODO: Consider using busybox instead of debian
+BASEIMAGE?=gcr.io/google-containers/debian-base-$(ARCH):0.2
+
 GO_BUILD       = env GOOS=$(PLATFORM) GOARCH=$(ARCH) go build -i $(GOFLAGS) \
-                   -ldflags "-X $(SC_PKG)/pkg.VERSION=$(VERSION)"
+                   -ldflags "-X $(SC_PKG)/pkg.VERSION=$(VERSION) $(BUILD_LDFLAGS)"
 BASE_PATH      = $(ROOT:/src/github.com/kubernetes-incubator/service-catalog/=)
 export GOPATH  = $(BASE_PATH):$(ROOT)/vendor
 
 MUTABLE_TAG                      ?= canary
-APISERVER_IMAGE                   = $(REGISTRY)apiserver:$(VERSION)
-APISERVER_MUTABLE_IMAGE           = $(REGISTRY)apiserver:$(MUTABLE_TAG)
-CONTROLLER_MANAGER_IMAGE          = $(REGISTRY)controller-manager:$(VERSION)
-CONTROLLER_MANAGER_MUTABLE_IMAGE  = $(REGISTRY)controller-manager:$(MUTABLE_TAG)
-USER_BROKER_IMAGE                 = $(REGISTRY)user-broker:$(VERSION)
-USER_BROKER_MUTABLE_IMAGE         = $(REGISTRY)user-broker:$(MUTABLE_TAG)
+SERVICE_CATALOG_IMAGE             = $(REGISTRY)service-catalog-$(ARCH):$(VERSION)
+SERVICE_CATALOG_MUTABLE_IMAGE     = $(REGISTRY)service-catalog-$(ARCH):$(MUTABLE_TAG)
+USER_BROKER_IMAGE                 = $(REGISTRY)user-broker-$(ARCH):$(VERSION)
+USER_BROKER_MUTABLE_IMAGE         = $(REGISTRY)user-broker-$(ARCH):$(MUTABLE_TAG)
 
 # precheck to avoid kubernetes-incubator/service-catalog#361
-$(if $(realpath vendor/k8s.io/kubernetes/vendor), \
-	$(error the vendor directory exists in the kubernetes \
+$(if $(realpath vendor/k8s.io/apimachinery/vendor), \
+	$(error the vendor directory exists in the apimachinery \
 		vendored source and must be flattened. \
 		run 'glide i -v'))
 
 ifdef UNIT_TESTS
 	UNIT_TEST_FLAGS=-run $(UNIT_TESTS) -v
+endif
+
+ifdef INT_TESTS
+	INT_TEST_FLAGS=--test.run=$(INT_TESTS)
+endif
+
+ifdef TEST_LOG_LEVEL
+	UNIT_TEST_FLAGS+=-v
+	UNIT_TEST_LOG_FLAGS=-args --alsologtostderr --v=$(TEST_LOG_LEVEL)
+	INT_TEST_FLAGS+=--alsologtostderr --v=$(TEST_LOG_LEVEL)
 endif
 
 ifdef NO_DOCKER
@@ -88,25 +106,22 @@ NON_VENDOR_DIRS = $(shell $(DOCKER_CMD) glide nv)
 
 # This section builds the output binaries.
 # Some will have dedicated targets to make it easier to type, for example
-# "apiserver" instead of "bin/apiserver".
+# "service-catalog" instead of "bin/service-catalog".
 #########################################################################
 build: .init .generate_files \
-       $(BINDIR)/controller-manager $(BINDIR)/apiserver \
-       $(BINDIR)/user-broker
+	$(BINDIR)/service-catalog \
+	$(BINDIR)/user-broker
 
-user-broker: .init $(BINDIR)/user-broker
-$(BINDIR)/user-broker: contrib/cmd/user-broker \
-	  $(shell find contrib/cmd/user-broker -type f)
+user-broker: $(BINDIR)/user-broker
+$(BINDIR)/user-broker: .init contrib/cmd/user-broker \
+	  $(shell find contrib/cmd/user-broker -type f) \
+	  $(shell find contrib/pkg/broker -type f)
 	$(DOCKER_CMD) $(GO_BUILD) -o $@ $(SC_PKG)/contrib/cmd/user-broker
 
-# We'll rebuild apiserver if any go file has changed (ie. NEWEST_GO_FILE)
-apiserver: .init $(BINDIR)/apiserver
-$(BINDIR)/apiserver: .generate_files cmd/apiserver $(NEWEST_GO_FILE)
-	$(DOCKER_CMD) $(GO_BUILD) -o $@ $(SC_PKG)/cmd/apiserver
-
-controller-manager: .init $(BINDIR)/controller-manager
-$(BINDIR)/controller-manager: .generate_files cmd/controller-manager $(NEWEST_GO_FILE)
-	$(DOCKER_CMD) $(GO_BUILD) -o $@ $(SC_PKG)/cmd/controller-manager
+# We'll rebuild service-catalog if any go file has changed (ie. NEWEST_GO_FILE)
+service-catalog: $(BINDIR)/service-catalog
+$(BINDIR)/service-catalog: .init .generate_files cmd/service-catalog $(NEWEST_GO_FILE)
+	$(DOCKER_CMD) $(GO_BUILD) -o $@ $(SC_PKG)/cmd/service-catalog
 
 # This section contains the code generation stuff
 #################################################
@@ -120,27 +135,27 @@ $(BINDIR)/controller-manager: .generate_files cmd/controller-manager $(NEWEST_GO
 	touch $@
 
 $(BINDIR)/defaulter-gen: .init
-	$(DOCKER_CMD) go build -o $@ $(SC_PKG)/vendor/k8s.io/kubernetes/cmd/libs/go2idl/defaulter-gen
+	$(DOCKER_CMD) go build -o $@ $(SC_PKG)/vendor/k8s.io/code-generator/cmd/defaulter-gen
 
 $(BINDIR)/deepcopy-gen: .init
-	$(DOCKER_CMD) go build -o $@ $(SC_PKG)/vendor/k8s.io/kubernetes/cmd/libs/go2idl/deepcopy-gen
+	$(DOCKER_CMD) go build -o $@ $(SC_PKG)/vendor/k8s.io/code-generator/cmd/deepcopy-gen
 
 $(BINDIR)/conversion-gen: .init
-	$(DOCKER_CMD) go build -o $@ $(SC_PKG)/vendor/k8s.io/kubernetes/cmd/libs/go2idl/conversion-gen
+	$(DOCKER_CMD) go build -o $@ $(SC_PKG)/vendor/k8s.io/code-generator/cmd/conversion-gen
 
 $(BINDIR)/client-gen: .init
-	$(DOCKER_CMD) go build -o $@ $(SC_PKG)/vendor/k8s.io/kubernetes/cmd/libs/go2idl/client-gen
+	$(DOCKER_CMD) go build -o $@ $(SC_PKG)/vendor/k8s.io/code-generator/cmd/client-gen
 
 $(BINDIR)/lister-gen: .init
-	$(DOCKER_CMD) go build -o $@ $(SC_PKG)/vendor/k8s.io/kubernetes/cmd/libs/go2idl/lister-gen
+	$(DOCKER_CMD) go build -o $@ $(SC_PKG)/vendor/k8s.io/code-generator/cmd/lister-gen
 
 $(BINDIR)/informer-gen: .init
-	$(DOCKER_CMD) go build -o $@ $(SC_PKG)/vendor/k8s.io/kubernetes/cmd/libs/go2idl/informer-gen
+	$(DOCKER_CMD) go build -o $@ $(SC_PKG)/vendor/k8s.io/code-generator/cmd/informer-gen
 
-$(BINDIR)/openapi-gen: vendor/k8s.io/kubernetes/cmd/libs/go2idl/openapi-gen
+$(BINDIR)/openapi-gen: vendor/k8s.io/code-generator/cmd/openapi-gen
 	$(DOCKER_CMD) go build -o $@ $(SC_PKG)/$^
 
-$(BINDIR)/e2e.test: .init
+$(BINDIR)/e2e.test: .init $(NEWEST_E2ETEST_SOURCE) $(NEWEST_GO_FILE)
 	$(DOCKER_CMD) go test -c -o $@ $(SC_PKG)/test/e2e
 
 # Regenerate all files if the gen exes changed or any "types.go" files changed
@@ -150,24 +165,25 @@ $(BINDIR)/e2e.test: .init
 		--v 1 --logtostderr \
 		--go-header-file "vendor/github.com/kubernetes/repo-infra/verify/boilerplate/boilerplate.go.txt" \
 		--input-dirs "$(SC_PKG)/pkg/apis/servicecatalog" \
-		--input-dirs "$(SC_PKG)/pkg/apis/servicecatalog/v1alpha1" \
+		--input-dirs "$(SC_PKG)/pkg/apis/servicecatalog/v1beta1" \
 	  	--extra-peer-dirs "$(SC_PKG)/pkg/apis/servicecatalog" \
-		--extra-peer-dirs "$(SC_PKG)/pkg/apis/servicecatalog/v1alpha1" \
+		--extra-peer-dirs "$(SC_PKG)/pkg/apis/servicecatalog/v1beta1" \
 		--output-file-base "zz_generated.defaults"
 	# Generate deep copies
 	$(DOCKER_CMD) $(BINDIR)/deepcopy-gen \
 		--v 1 --logtostderr \
 		--go-header-file "vendor/github.com/kubernetes/repo-infra/verify/boilerplate/boilerplate.go.txt" \
 		--input-dirs "$(SC_PKG)/pkg/apis/servicecatalog" \
-		--input-dirs "$(SC_PKG)/pkg/apis/servicecatalog/v1alpha1" \
+		--input-dirs "$(SC_PKG)/pkg/apis/servicecatalog/v1beta1" \
 		--bounding-dirs "github.com/kubernetes-incubator/service-catalog" \
 		--output-file-base zz_generated.deepcopy
 	# Generate conversions
 	$(DOCKER_CMD) $(BINDIR)/conversion-gen \
 		--v 1 --logtostderr \
+		--extra-peer-dirs k8s.io/api/core/v1,k8s.io/apimachinery/pkg/apis/meta/v1,k8s.io/apimachinery/pkg/conversion,k8s.io/apimachinery/pkg/runtime \
 		--go-header-file "vendor/github.com/kubernetes/repo-infra/verify/boilerplate/boilerplate.go.txt" \
 		--input-dirs "$(SC_PKG)/pkg/apis/servicecatalog" \
-		--input-dirs "$(SC_PKG)/pkg/apis/servicecatalog/v1alpha1" \
+		--input-dirs "$(SC_PKG)/pkg/apis/servicecatalog/v1beta1" \
 		--output-file-base zz_generated.conversion
 	# generate all pkg/client contents
 	$(DOCKER_CMD) $(BUILD_DIR)/update-client-gen.sh
@@ -175,10 +191,8 @@ $(BINDIR)/e2e.test: .init
 	$(DOCKER_CMD) $(BINDIR)/openapi-gen \
 		--v 1 --logtostderr \
 		--go-header-file "vendor/github.com/kubernetes/repo-infra/verify/boilerplate/boilerplate.go.txt" \
-		--input-dirs "github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/v1alpha1,k8s.io/client-go/pkg/api/v1,k8s.io/apimachinery/pkg/apis/meta/v1" \
+		--input-dirs "github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/v1beta1,k8s.io/api/core/v1,k8s.io/apimachinery/pkg/apis/meta/v1" \
 		--output-package "github.com/kubernetes-incubator/service-catalog/pkg/openapi"
-	# generate codec
-	$(DOCKER_CMD) $(BUILD_DIR)/update-codecgen.sh
 	touch $@
 
 # Some prereq stuff
@@ -197,9 +211,10 @@ $(BINDIR)/e2e.test: .init
 .PHONY: verify verify-client-gen
 verify: .init .generate_files verify-client-gen
 	@echo Running gofmt:
-	@$(DOCKER_CMD) gofmt -l -s $(TOP_SRC_DIRS) > .out 2>&1 || true
-	@bash -c '[ "`cat .out`" == "" ] || \
-	  (echo -e "\n*** Please 'gofmt' the following:" ; cat .out ; echo ; false)'
+	@$(DOCKER_CMD) gofmt -l -s $(TOP_TEST_DIRS) $(TOP_SRC_DIRS)>.out 2>&1||true
+	@[ ! -s .out ] || \
+	  (echo && echo "*** Please 'gofmt' the following:" && \
+	  cat .out && echo && rm .out && false)
 	@rm .out
 	@#
 	@echo Running golint and go vet:
@@ -207,9 +222,10 @@ verify: .init .generate_files verify-client-gen
 	@# observes conventions from upstream that will not pass lint checks).
 	@$(DOCKER_CMD) sh -c \
 	  'for i in $$(find $(TOP_SRC_DIRS) -name *.go \
+	    | grep -v ^pkg/kubernetes/ \
 	    | grep -v generated \
 	    | grep -v ^pkg/client/ \
-	    | grep -v v1alpha1/defaults.go); \
+	    | grep -v v1beta1/defaults.go); \
 	  do \
 	   golint --set_exit_status $$i || exit 1; \
 	  done'
@@ -217,11 +233,11 @@ verify: .init .generate_files verify-client-gen
 	$(DOCKER_CMD) go vet $(NON_VENDOR_DIRS)
 	@echo Running repo-infra verify scripts
 	@$(DOCKER_CMD) vendor/github.com/kubernetes/repo-infra/verify/verify-boilerplate.sh --rootdir=. | grep -v generated > .out 2>&1 || true
-	@bash -c '[ "`cat .out`" == "" ] || (cat .out ; false)'
+	@[ ! -s .out ] || (cat .out && rm .out && false)
 	@rm .out
 	@#
 	@echo Running href checker:
-	@$(DOCKER_CMD) verify-links.sh .
+	@$(DOCKER_CMD) verify-links.sh -t .
 	@echo Running errexit checker:
 	@$(DOCKER_CMD) build/verify-errexit.sh
 
@@ -237,17 +253,30 @@ coverage: .init
 
 test: .init build test-unit test-integration
 
+# this target checks to see if the go binary is installed on the host
+.PHONY: check-go
+check-go:
+	@if [ -z $$(which go) ]; then \
+	  echo "Missing \`go\` binary which is required for development"; \
+	  exit 1; \
+	fi
+
+# this target uses the host-local go installation to test 
+.PHONY: test-unit-native
+test-unit-native: check-go
+	go test $(addprefix ${SC_PKG}/,${TEST_DIRS})
+
 test-unit: .init build
 	@echo Running tests:
 	$(DOCKER_CMD) go test -race $(UNIT_TEST_FLAGS) \
-	  $(addprefix $(SC_PKG)/,$(TEST_DIRS))
+	  $(addprefix $(SC_PKG)/,$(TEST_DIRS)) $(UNIT_TEST_LOG_FLAGS)
 
 test-integration: .init $(scBuildImageTarget) build
 	# test kubectl
 	contrib/hack/setup-kubectl.sh
 	contrib/hack/test-apiserver.sh
 	# golang integration tests
-	$(DOCKER_CMD) test/integration.sh
+	$(DOCKER_CMD) test/integration.sh $(INT_TEST_FLAGS)
 
 clean-e2e:
 	rm -f $(BINDIR)/e2e.test
@@ -258,11 +287,11 @@ test-e2e: .generate_files $(BINDIR)/e2e.test
 clean: clean-bin clean-build-image clean-generated clean-coverage
 
 clean-bin:
-	rm -rf $(BINDIR)
+	$(DOCKER_CMD) rm -rf $(BINDIR)
 	rm -f .generate_exes
 
 clean-build-image:
-	rm -rf .pkg
+	$(DOCKER_CMD) rm -rf .pkg
 	rm -f .scBuildImage
 	docker rmi -f scbuildimage > /dev/null 2>&1 || true
 
@@ -285,47 +314,74 @@ purge-generated:
 	find $(TOP_SRC_DIRS) -name zz_generated* -exec rm {} \;
 	find $(TOP_SRC_DIRS) -type d -name *_generated -exec rm -rf {} \;
 	rm -f pkg/openapi/openapi_generated.go
-	echo 'package v1alpha1' > pkg/apis/servicecatalog/v1alpha1/types.generated.go
+	echo 'package v1beta1' > pkg/apis/servicecatalog/v1beta1/types.generated.go
 
 clean-coverage:
 	rm -f $(COVERAGE)
 
 # Building Docker Images for our executables
 ############################################
-images: user-broker-image \
-    controller-manager-image apiserver-image
+images: user-broker-image service-catalog-image
+
+images-all: $(addprefix arch-image-,$(ALL_ARCH))
+arch-image-%:
+	$(MAKE) clean-bin
+	$(MAKE) ARCH=$* build
+	$(MAKE) ARCH=$* images
 
 define build-and-tag # (service, image, mutable_image, prefix)
 	$(eval build_path := "$(4)build/$(1)")
 	$(eval tmp_build_path := "$(build_path)/tmp")
 	mkdir -p $(tmp_build_path)
 	cp $(BINDIR)/$(1) $(tmp_build_path)
-	docker build -t $(2) $(build_path)
+	cp $(build_path)/Dockerfile $(tmp_build_path)
+	# -i.bak is required for cross-platform compat: https://stackoverflow.com/questions/5694228/sed-in-place-flag-that-works-both-on-mac-bsd-and-linux
+	sed -i.bak "s|BASEIMAGE|$(BASEIMAGE)|g" $(tmp_build_path)/Dockerfile
+	rm $(tmp_build_path)/Dockerfile.bak
+	docker run --rm --privileged multiarch/qemu-user-static:register --reset
+	docker build -t $(2) $(tmp_build_path)
 	docker tag $(2) $(3)
 	rm -rf $(tmp_build_path)
 endef
 
 user-broker-image: contrib/build/user-broker/Dockerfile $(BINDIR)/user-broker
 	$(call build-and-tag,"user-broker",$(USER_BROKER_IMAGE),$(USER_BROKER_MUTABLE_IMAGE),"contrib/")
+ifeq ($(ARCH),amd64)
+	docker tag $(USER_BROKER_IMAGE) $(REGISTRY)user-broker:$(VERSION)
+	docker tag $(USER_BROKER_MUTABLE_IMAGE) $(REGISTRY)user-broker:$(MUTABLE_TAG)
+endif
 
-apiserver-image: build/apiserver/Dockerfile $(BINDIR)/apiserver
-	$(call build-and-tag,"apiserver",$(APISERVER_IMAGE),$(APISERVER_MUTABLE_IMAGE))
+service-catalog-image: build/service-catalog/Dockerfile $(BINDIR)/service-catalog
+	$(call build-and-tag,"service-catalog",$(SERVICE_CATALOG_IMAGE),$(SERVICE_CATALOG_MUTABLE_IMAGE))
+ifeq ($(ARCH),amd64)
+	docker tag $(SERVICE_CATALOG_IMAGE) $(REGISTRY)service-catalog:$(VERSION)
+	docker tag $(SERVICE_CATALOG_MUTABLE_IMAGE) $(REGISTRY)service-catalog:$(MUTABLE_TAG)
+endif
 
-controller-manager-image: build/controller-manager/Dockerfile $(BINDIR)/controller-manager
-	$(call build-and-tag,"controller-manager",$(CONTROLLER_MANAGER_IMAGE),$(CONTROLLER_MANAGER_MUTABLE_IMAGE))
 
 # Push our Docker Images to a registry
 ######################################
-push: user-broker-push controller-manager-push apiserver-push
+push: user-broker-push service-catalog-push
 
 user-broker-push: user-broker-image
 	docker push $(USER_BROKER_IMAGE)
 	docker push $(USER_BROKER_MUTABLE_IMAGE)
+ifeq ($(ARCH),amd64)
+	docker push $(REGISTRY)user-broker:$(VERSION)
+	docker push $(REGISTRY)user-broker:$(MUTABLE_TAG)
+endif
 
-controller-manager-push: controller-manager-image
-	docker push $(CONTROLLER_MANAGER_IMAGE)
-	docker push $(CONTROLLER_MANAGER_MUTABLE_IMAGE)
+service-catalog-push: service-catalog-image
+	docker push $(SERVICE_CATALOG_IMAGE)
+	docker push $(SERVICE_CATALOG_MUTABLE_IMAGE)
+ifeq ($(ARCH),amd64)
+	docker push $(REGISTRY)service-catalog:$(VERSION)
+	docker push $(REGISTRY)service-catalog:$(MUTABLE_TAG)
+endif
 
-apiserver-push: apiserver-image
-	docker push $(APISERVER_IMAGE)
-	docker push $(APISERVER_MUTABLE_IMAGE)
+
+release-push: $(addprefix release-push-,$(ALL_ARCH))
+release-push-%:
+	$(MAKE) clean-bin
+	$(MAKE) ARCH=$* build
+	$(MAKE) ARCH=$* push
